version: '3.8'
services:
  todo-frontend:
    build: ./frontend  
    ports:
      - "5173:5173"
    depends_on:
      - todo-freight 
  todo-freight:
    build: ./  
    ports:
      - "5002:5002" 
    extra_hosts:
      - "host.docker.internal:host-gateway"